/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f103xb.h"
#include <string.h>

#define MAX_LEN 100

uint8_t rxBuffer[MAX_LEN];
uint8_t dataLength = 0;

void SPI1_GPIO_Init(void)
{
    RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;

    // PA5 -> SCK input floating
    GPIOA->CRL &= ~(0xF << 20);
    GPIOA->CRL |=  (0x4 << 20);

    // PA7 -> MOSI input floating
    GPIOA->CRL &= ~(0xF << 28);
    GPIOA->CRL |=  (0x4 << 28);

    // PA6 -> MISO AF push-pull
    GPIOA->CRL &= ~(0xF << 24);
    GPIOA->CRL |=  (0xB << 24);

    // PA4 -> NSS input floating
    GPIOA->CRL &= ~(0xF << 16);
    GPIOA->CRL |=  (0x4 << 16);
}

void SPI1_Init(void)
{
    RCC->APB2ENR |= RCC_APB2ENR_SPI1EN;

    SPI1->CR1 = 0;

    SPI1->CR1 &= ~(SPI_CR1_MSTR);  // Slave
    SPI1->CR1 &= ~(SPI_CR1_CPOL);
    SPI1->CR1 &= ~(SPI_CR1_CPHA);
    SPI1->CR1 &= ~(SPI_CR1_DFF);   // 8-bit
    SPI1->CR1 &= ~(SPI_CR1_SSM);   // Hardware NSS

    SPI1->CR1 |= SPI_CR1_SPE;      // Enable SPI
}

void LED_Init(void)
{
    RCC->APB2ENR |= RCC_APB2ENR_IOPCEN;

    GPIOC->CRH &= ~(0xF << 20);
    GPIOC->CRH |=  (0x2 << 20);  // PC13 output
    GPIOC->ODR |= (1 << 13);      // LED off
}

void LED_Toggle(void)
{
    GPIOC->ODR ^= (1 << 13);
}

int main(void)
{
    uint8_t i;

    LED_Init();
    SPI1_GPIO_Init();
    SPI1_Init();

    while(1)
    {
        // 1️⃣ Length byte bekle
        while(!(SPI1->SR & SPI_SR_RXNE));
        dataLength = SPI1->DR;

        if(dataLength > MAX_LEN)
            dataLength = MAX_LEN;

        // 2️⃣ String byte'larını al
        for(i = 0; i < dataLength; i++)
        {
            while(!(SPI1->SR & SPI_SR_RXNE));
            rxBuffer[i] = SPI1->DR;
        }

        // Null terminate (string güvenliği)
        rxBuffer[dataLength] = '\0';

        // 3️⃣ LED toggle: her master verisi geldiğinde durumu değişir
        LED_Toggle();

        // rxBuffer artık gelen stringi tutuyor
        // Eğer terminal veya debug ile görmek istersen breakpoint koyabilirsin
    }
}
