/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f103xb.h"

#define BUFFER_SIZE 100

volatile uint8_t rxBuffer[BUFFER_SIZE];
volatile uint8_t rxIndex = 0;

void SPI1_GPIO_Init(void) {
    // PA5->SCK, PA6->MISO, PA7->MOSI, PA4->NSS
    RCC->APB2ENR |= RCC_APB2ENR_IOPAEN; // GPIOA clock enable

    // PA5 SCK input floating (slave)
    GPIOA->CRL &= ~(0xF << (5*4));
    GPIOA->CRL |=  (0x4 << (5*4));

    // PA6 MISO output push-pull
    GPIOA->CRL &= ~(0xF << (6*4));
    GPIOA->CRL |=  (0x1 << (6*4)); // 10: Output 2 MHz push-pull
    GPIOA->CRL |=  (0x2 << (6*4)); // Actually for 2MHz

    // PA7 MOSI input floating
    GPIOA->CRL &= ~(0xF << (7*4));
    GPIOA->CRL |=  (0x4 << (7*4));

    // PA4 NSS input floating
    GPIOA->CRL &= ~(0xF << (4*4));
    GPIOA->CRL |=  (0x4 << (4*4));
}

void SPI1_Init(void) {
    RCC->APB2ENR |= RCC_APB2ENR_SPI1EN; // SPI1 clock enable

    SPI1->CR1 = 0;
    SPI1->CR1 |= SPI_CR1_SPE;  // SPI enable
    SPI1->CR1 &= ~SPI_CR1_MSTR; // Slave mode
    SPI1->CR1 &= ~SPI_CR1_CPOL;
    SPI1->CR1 &= ~SPI_CR1_CPHA;
    SPI1->CR1 &= ~SPI_CR1_LSBFIRST;
    SPI1->CR1 &= ~SPI_CR1_SSI; // Hardware NSS
    SPI1->CR1 &= ~SPI_CR1_BR;  // SCLK not used in slave
}

uint8_t SPI1_Receive(void) {
    while(!(SPI1->SR & SPI_SR_RXNE));
    return SPI1->DR;
}

int main(void) {
    SPI1_GPIO_Init();
    SPI1_Init();

    while(1) {
        // veri geldi mi kontrol et
        if(SPI1->SR & SPI_SR_RXNE) {
            uint8_t data = SPI1_Receive();
            if(rxIndex < BUFFER_SIZE) {
                rxBuffer[rxIndex++] = data;
            }
        }
    }
}
